### ISSUE TITLE
Does not seem to work on El Capitan!

### ISSUE THREAD

**Issue by morfinrider** [w0lfschild/Flashlight#11]
I installed your fork of Flashlight on El Capitan and then installed some common plugins like IS IT UP?, SHOW HIDDEN FILES, and many more. None of the plugins seem to work. When I type in Spotlight search, default Spotlight search works. Can you help resolve? TIA!

**Comment by w0lfschild** [comment]
Have you installed [mySIMBL](https://github.com/w0lfschild/mySIMBL) first? Flashlight needs mySIMBL properly installed to function.
