### ISSUE TITLE
How do I add my own plugins?

### ISSUE THREAD

**Issue by ghost** [w0lfschild/Flashlight#16]
I've been developing some plugins for Flashlight, and soon at least one of them will be ready to share.

However, I don't know how to actually add my plugin to Flashlight.

I don't find the instructions very clear:

> Once you're finished with a plugin, clone our repo, place your bundle in PluginDirectories/1, and we'll upload it to the online directory.

Do you mean fork and then submit a pull request?

**Comment by w0lfschild** [comment]
Yes. Look at any of the closed pull requests for an example.

https://github.com/w0lfschild/Flashlight/pulls?q=is%3Apr+is%3Aclosed
