### ISSUE TITLE
Flashlight crashed if I entered `w` as the first word.

### ISSUE THREAD

**Issue by kxxoling** [w0lfschild/Flashlight#17]
It works after I uninstalled both wikipedia plugin and weather plugin. It does not work if I only uninstall  one of them.  Log here:

```
Jan 15 03:03:59 MacBook-Pro Squirrel[424]: createSession: com.apple.Spotlight
Jan 15 03:03:59 MacBook-Pro com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Jan 15 03:03:59 MacBook-Pro Squirrel[424]: setAppOptions: com.apple.Spotlight
Jan 15 03:04:01 MacBook-Pro com.apple.xpc.launchd[1] (com.apple.ReportCrash[3980]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.ReportCrash
```

I'm using macOS 10.12 the newest on Macbook 2016 15'.

**Comment by MatthD** [comment]
Hello,

This is the same bug when we want to use man : It just crash

**Comment by kxxoling** [comment]
I found more crashes if I input `sh` or `dd`, it's also solved by uninstalling related plugins. I think there should be some process to prevent it just crashing when there's error with plugins.

**Comment by w0lfschild** [comment]
Okay I know why this is happening but this whole project in general is going to need some updating which I probably won't have to much time for, at least not anytime soon.

This issue is because of a change in `SPGroupHeadingResult` from

`- (id)initWithDisplayName:(id)arg1 focusString:(id)arg2` 
to 
`- (id)initWithDisplayName:(id)arg1 keyID:(id)arg2 focusString:(id)arg3`

**Comment by manegame** [comment]
For me on MacOS Sierra 10.12.3 this is also happening for strings "/", "at", "cal", "man", "tr", "log", any string containing ".", and more.

**Comment by Ngalstyan4** [comment]
@w0lfschild could you please at least share an outline of what needs to be done to fix the issue and someone from the community will contribute a patch?
I am personally willing to do this provided I understand the problem.

**Comment by w0lfschild** [comment]
@Ngalstyan4 I'm not sure if there's more to say then what I posted above. 

I've already fixed the issue for the next build.

_FlashlightPluginEngine.m
```objective-c
if ([NSClassFromString(@"SPGroupHeadingResult") instancesRespondToSelector:@selector(initWithDisplayName:focusString:)])
    [pluginNonTopHits insertObject:[[NSClassFromString(@"SPGroupHeadingResult") alloc] initWithDisplayName:@"FLASHLIGHT" focusString:nil] atIndex:0];
else
    [pluginNonTopHits insertObject:[[NSClassFromString(@"SPGroupHeadingResult") alloc] initWithDisplayName:@"FLASHLIGHT" keyID:nil focusString:nil] atIndex:0];
```

**Comment by vin047** [comment]
Temporary fix based on @w0lfschild comments. 

Replace `Flashlight.app/Contents/Resources/SpotlightSIMBL.bundle` with the attached bundle. Seems to be working for me with no issues so far.

[SpotlightSIMBL.bundle.zip](https://github.com/w0lfschild/Flashlight/files/906907/SpotlightSIMBL.bundle.zip)

**Comment by vin047** [comment]
Spoke too soon - seems to be crashing on my other Mac 😢

@w0lfschild any ETA on a fix?

**Comment by w0lfschild** [comment]
Should be fixed in the latest release.

**Comment by funkyLover** [comment]
@w0lfschild great work! thank you!
