### ISSUE TITLE
It's not working on El Capitan

### ISSUE THREAD

**Issue by escobar5** [w0lfschild/Flashlight#2]
I just tried to install following instructions in readme, but flashlight doesn't work, sometimes it does nothing, and sometimes spotlight freezes. Any ideas?

**Comment by escobar5** [comment]
Nevermind, It seems I needed to enable system protection again (csrutil enable) for it to work.

**Comment by escobar5** [comment]
Well, not exactly, it just worked for one time, then its crashing again.

I'm on OS X 10.11.5

**Comment by w0lfschild** [comment]
How is it crashing? Is it when you're using a specific plugin or just as soon as you open Spotlight?

**Comment by escobar5** [comment]
When using any plugin, emoji for example, it freezes, then restarts

**Comment by Sajonara** [comment]
Same here. Spotlight just disappears, after I reboot and SIP is enabled again. I have to reboot, disable it, install everything again and it's working once, but when I restart my machine or even wake it up from sleep Spotlight crashes and I can no longer use Flashlight. But I am under macOS Sierra.

Update: I noticed, that when I restart the machine, everything is working correctly again. The system cannot be used directly but after some seconds, when Spotlight has settled, I can use Flashlight. If you have any idea what I can test, to give you proper feedback, just tell.

PS: Under Sierra I am not shown a menubar icon though it is checked in Flashlight's preferences. Unchecking it changes nothing.

Kind regards.

**Comment by w0lfschild** [comment]
@Sajonara 

Instead of doing all that just open terminal and run:

`osascript -e "tell application \"Spotlight\" to inject SIMBL into Snow Leopard"`

I need to update mySIMBL for 10.12

**Comment by Sajonara** [comment]
I did what you told me to do. And I rebooted my system. It seems to work just fine. Awesome. Thanks a lot.

So just to understand it, you're using an AppleScript snippet to inject SIMBL, but why do you address "Snow Leopard"? And as I don't have too much knowledge of it, how is "Dock" involved into this?

**Comment by w0lfschild** [comment]
Whoops that was supposed to say `Spotlight` instead of `Dock`.

It's Snow Leopard because that's the keyword that SIMBL is written to accept.

**Comment by ghost** [comment]
Tried the Terminal command, rebooted. Flashlight works the FIRST time I open the search bar. If I try it again, the bar vanishes after af few seconds (almost like a crash), and when pulling it up again the Flashlight stuff is gone. I'm still on El Capitan, hope you can help (can I log something for you?) Cheers.

**Comment by w0lfschild** [comment]
Well it probably is crashing. You do not need to reboot to reload Flashlight though.

Just run `osascript -e "tell application \"Spotlight\" to inject SIMBL into Snow Leopard"` from terminal and it will be re-applied.

**Comment by w0lfschild** [comment]
Update out for mySIMBL (v0.3.0) which should now load into Spotlight automatically.

**Comment by ghost** [comment]
Thanks, will try updating (and did use the command actually, much easier
yes ;) )

Cheers

**Comment by ghost** [comment]
Tried to update. Still the crashing issue. The only plugin that actually do work at all times is the quick web search plugin. All others crash the Spotlight search bar after I type a few letters of the keyword, (emoji, shutdown etc.). Not really sure what can be done about this, it seems both mySIMBL and Flashlight installs correctly, I followed the instructions re. system integrity disable etc. of course.

**Comment by w0lfschild** [comment]
Is there a crash dialog that pops up? Or any information in console related to the crashing?
