### ISSUE TITLE
Weather plugin does not work

### ISSUE THREAD

**Issue by mrtmiller** [w0lfschild/Flashlight#20]
Hi there, been using Flashlight on a brand new rMBP 2015, everything updated. Pretty much first thing I did was install mySIMBL and Flashlight - and everything works so far, except for the weather plugin. 

"How's the weather in XXX, yy?" returns the following:

> Loading
> ???
> 

Any thoughts?

**Comment by tsimmons** [comment]
The weather plugin doesn't work out of the box. I had to modify it a bit to make it work (changes in openweathermap's policy require an API ID to use the service.) I could *post* the changes if you're interested.

**Comment by mrtmiller** [comment]
Is an API ID easy to ahold of? I'm above average technical, so try me :p

**Comment by tsimmons** [comment]
Yup. Goto http://openweathermap.org/ and signup, get your ID. I'm attaching a diff for the changes to ~/Library/FlashlightPlugins/weather.bundle/weather.html

Insert your API ID in place of INSERT_YOUR_APP_ID in the diff before applying.

[weather.diff](https://gist.github.com/tsimmons/75165b26cc2688cf9141a8a32af667bc)

**Comment by mrtmiller** [comment]
Thanks that worked! It took awhile for me as a complete Mac newb to find out how to patch files with terminal but hey, learning by doing haha.

**Comment by Roy75117** [comment]
I follow this post(apply diff and replace with my API ID) but it is still in vain. It there any other workaround to fix this issue?

**Comment by tsimmons** [comment]
What do you see in the Spotlight preview window? Occasionally openweathermap.org returns *502 Bad Gateway* if they are under load and if that is the case, you will usually see the URL displayed instead of the weather or the "Loading" screen.

**Comment by Roy75117** [comment]
![2017-02-21 06 25 41](https://cloud.githubusercontent.com/assets/6182550/23142294/9da4a6a6-f7fe-11e6-8242-7a5b0cdc1860.png)

I only see Loading instead of any other error

**Comment by tsimmons** [comment]
I suspect you haven't either made the changes properly or you need to reboot. 

<img width="687" alt="screen shot 2017-02-20 at 3 57 07 pm" src="https://cloud.githubusercontent.com/assets/366120/23143127/5c386e56-f785-11e6-8966-ec9cd6411b70.png">

**Comment by Roy75117** [comment]
I modified the wrong file.
It is weather.bundle but weather.disabled-bundle.
Now issue fixed. Thanks so much

![2017-02-21 20 01 25](https://cloud.githubusercontent.com/assets/6182550/23162250/8d37c452-f870-11e6-9570-101114bcc389.png)

**Comment by hh253996728** [comment]
@mrtmiller Sorry, still a little confused about how to apply weather.diff to ~/Library/FlashlightPlugins/weather.bundle/weather.html
I'm such a Mac newb. 😂😂😂

**Comment by bbbenji** [comment]
@hh253996728 

`patch -p1 < weather.diff`
