### ISSUE TITLE
Duplicate Kill Plugins

### ISSUE THREAD

**Issue by ibrokemypie** [w0lfschild/Flashlight#25]
<img width="443" alt="screen shot 2017-03-11 at 3 17 20 pm" src="https://cloud.githubusercontent.com/assets/7827846/23820508/f3fd5fde-066d-11e7-8d46-6b513df6830b.png">
Why are there two "Kill" plugins? Is there a functional difference between them? Which should be used?

**Comment by w0lfschild** [comment]
Dunno. I don't host the plugins that's still [Nate Parrott](https://github.com/nate-parrott).
