### ISSUE TITLE
Plugin Repo

### ISSUE THREAD

**Issue by ibrokemypie** [w0lfschild/Flashlight#28]
I propose removal of the inbuilt plugins and moving them all to a separate github repo with numerous members who may accept pull requests. This makes it easier for people to make their own changes and editions + updates to plugins more easily without requiring forking the who of Flashlight, and can make a cleaner, more manageable collection, all together. Somewhat like homebrew and cask.

**Comment by w0lfschild** [comment]
The project would need to be reworked. I've really only been maintaining the SIMBL bundle to keep it from crashing.

Doubt this is something I'd be willing to do. As the effort vs payoff ($0) wouldn't be worthwhile to me as I personally don't have any need for what you're suggesting.

If someone want to fork this and implement that they could.
