### ISSUE TITLE
plugins not working after SIMBL installed

### ISSUE THREAD

**Issue by zhenyulin** [w0lfschild/Flashlight#29]
disabled SIP and installed SIMBL, in Spotlight when typing `text someone something`, it shows a preview but won't do anything when I hit the enter. Is there something I missed during the setup?

**Comment by ghost** [comment]
experiencing the same issue... bump
btw INCREDIBLE WORK HERE w0lfschild! missed flashlight sooo much!!!!

**Comment by zhenyulin** [comment]
has anyone identified the cause for this?
