### ISSUE TITLE
Some plugins are not functional

### ISSUE THREAD

**Issue by 99z** [w0lfschild/Flashlight#3]
Have mySIMBL installed with no issues. SpotlightSIMBL appears in the Plugins list, and `Console.app` logs a "Hello from Flashlight!" message. Other plugins installed via mySIMBL are working fine.

No crashes or anything when installing/uninstalling plugins. Plugins simply don't do anything - installing any plugin, e.g. the Emoji plugin, then searching for an emoji do nothing. Spotlight behaves as if the plugin doesn't exist - or Flashlight isn't working properly.

**Comment by 99z** [comment]
Noticing now that certain plugins seem to work? Quick Web Search is working, so is Create a Note. Could this be an issue on the plugin end?

**Comment by w0lfschild** [comment]
Not sure sounds like a plugin issue. I'm sure some have probably broken since they were originally implemented. 

Make sure you're also using the right keywords to trigger the plugin. The emoji plugin works fine for me on 10.12

![screen shot 2016-07-07 at 8 45 24 am](https://cloud.githubusercontent.com/assets/1920148/16659523/4ae1fe66-441f-11e6-8610-0050cdd1dcfe.png)

**Comment by 99z** [comment]
Are there any sort of logs I'd be able to examine? Really strange I'm having issues - here's Quick Web Search working:

![screen shot 2016-07-07 at 11 59 35 am](https://cloud.githubusercontent.com/assets/7397825/16660039/c2d7577a-443a-11e6-9ba4-4bad243a6214.png)

And here's emojis not working:

![screen shot 2016-07-07 at 11 59 57 am](https://cloud.githubusercontent.com/assets/7397825/16660051/d13d9dba-443a-11e6-9456-e13d4eb920f5.png)

Notes work as well, and I even get the following notification:

![screen shot 2016-07-07 at 12 04 32 pm](https://cloud.githubusercontent.com/assets/7397825/16660105/05649bfc-443b-11e6-936a-ac4fe0a77c62.png)

**Comment by w0lfschild** [comment]
Maybe try deleting your flashlight plugins `~/Library/FlashlightPlugins` and re-installing?

**Comment by coreonyx** [comment]
My Weather Plugin not working as well

<img width="683" alt="test" src="https://cloud.githubusercontent.com/assets/6238633/18620807/401c2704-7e5d-11e6-92e3-1a2594bcdfb6.png">

**Comment by coreonyx** [comment]
probably **weather.html** didn't get the value passed from the **plugin.py**

**Comment by w0lfschild** [comment]
Yes some plugins are broken. I probably won't personally be doing any work to fix any plugins.

**Comment by YonatanAhituv** [comment]
@coreonyx The weather plugin is the one unfixable plugin, at least, easily, `openweathermap`, what the plugin uses requires an API key. I've been able to fix it with my own API key. But personal ones have limitations and commercial ones are expensive.
But, either way, MacOS has it's own weather info in spotlight now, so why continue working on a seperate one?
