### ISSUE TITLE
"Enter" does not work

### ISSUE THREAD

**Issue by chenghuzi** [w0lfschild/Flashlight#30]
When using plugins like bing search and baidu search, they tell me to enter to see the results in the browser. But nothing happened after I pressed "enter".

**Comment by iiiGerardoiii** [comment]
I don't have any search plugins for Flashlight installed to reproduce your issue, but you could press Cmd+B to send the typed text to your browser's search engine. This workaround comes by default on Spotlight but it's not well known.
