### ISSUE TITLE
Flashlight commands suddenly not working in 10.12.6 Spotlight

### ISSUE THREAD

**Issue by elnygren** [w0lfschild/Flashlight#35]
I've followed all instructions in this repository and I got Flashlight working. However, suddenly today none of my Flashlight commands are working (none of the commands are found in Spotlight, only standard Spotlight search results).

How do I debug this? Anything I should be looking for in Flashlight, mySIMBL or some logs somewhere?

**Comment by zhongqin0820** [comment]
me too,  and i can't install SIMBL..
![](http://ovnuv29fq.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202017-10-04%2001.02.09.png)

**Comment by limitLiu** [comment]
@zhongqin0820  On macOS 10.12.6, you can disable csrutil to install SIMBL. How to disable csrutil? Google it.
