### ISSUE TITLE
Some plugins can't work on macOS 10.13

### ISSUE THREAD

**Issue by limitLiu** [w0lfschild/Flashlight#36]
All plugins are ok on macOS 10.12.6, but on macOS 10.13, some plugins can work, others can't work.

**Comment by chenghuzi** [comment]
It seems that almost all plugins can not work.

**Comment by imYerik** [comment]
It seems that almost all plugins can not work. sad :(

**Comment by fuorviatos** [comment]
Sadly, almost all of them do not work and the dev of flashlight stated openly he's not gonna work on fixing them.

**Comment by ghost** [comment]
@fuorviatos Where did w0lfschild say that?

**Comment by czjxy881** [comment]
+1

**Comment by mapping77** [comment]
Well, the same problem, it seems all plugins don't work.

**Comment by technolingo** [comment]
This is the problem with open source software. Make it commercial and I would definitely buy it.

**Comment by mkormendy** [comment]
Yeah I'd pay $20 for it.

**Comment by w0lfschild** [comment]
Unfortunately I don't really know much about the plugins. This was mainly just meant to fix a few issues that were causing the application to crash.

For me to really do work on this the project would need to separate itself from the original Flashlight servers because right now I can't even push pull request for plugins because the application is pulling from the original server.

I'd gladly take help on this project and keep it free though.

**Comment by krystofcelba** [comment]
Hi,
I have investigated a bit why plugins do not work on macOS 10.13 and seem I got it finally works again.

- PR -  #41 
- New build with fix  - [Flashlight v1.0.7](http://bit.ly/2GsH6g1).

Feedback welcomed.

![Flashlight macOS 10.13](https://user-images.githubusercontent.com/250009/37461110-a640e902-284d-11e8-87ec-f845d4ac86f6.gif)

**Comment by w0lfschild** [comment]
Dang that's 🔥. I'll check it out this weekend and as long as it doesn't break prior compatibility I'll merge it and put out an update.

**Comment by waxfingers** [comment]
Seems to be working (macos 10.13.3)... so cool and I had given up on Flashlight and MySimbl, back from the dead and hungry as hell!!! Thank you @krystofcelba and @w0lfschild 🐙⚡️🍄🌱🐉

**Comment by krystofcelba** [comment]
@w0lfschild I've just tested it on macOS 10.12 and seems work well too. Unfortunately, I don’t have access to an older system where I could prove it. I could probably add some runtime checks, so it uses the old methods in case the new ones are not available.

@waxfingers Good to hear 🙂. In my opinion, there isn't still anything which could concur Flashlight. I'm thinking of that would be great to reinstate some of its infrastructures so it will be easier to bring up new things etc. Something like "Flashlight Reloaded" 😄.

**Comment by waxfingers** [comment]
Yup REloAD alright!! I got drunk and lost, went on knocking at zazu, cerebro, alfred, lacona and even launchbar's door... just to end up drinking alone in a cold, empty alley... there's something about flashlight, a dynamic sparkle, something about the way it crawls and wants to live through the OS' mother tree... that is beautiful, frightening, inspiring and unique... well maybe it's just me 🐒{emoji copied through FL's plugin} ,-)   
   
Even xtrafinder came back from the dead through FL
![xtrafinder_flashlight_mysimbl_web](https://user-images.githubusercontent.com/13238340/37494021-fe411d7e-289e-11e8-9687-42874edeb7fd.jpg)

**Comment by mkormendy** [comment]
What the hell?

**Comment by krystofcelba** [comment]
@w0lfschild  I've committed some changes, it now checks the OS version and reloads the results differently only on ^10.13, so it now shouldn't break anything in prior OS versions hopefully 🙏.

@waxfingers  I've thought that I’m reading part of [_Howl_](https://www.poetryfoundation.org/poems/49303/howl) for a little while 👍 😅. But I think that I had very similar experience.

**Comment by faicker** [comment]
work like a charm for 10.13.3 😄

**Comment by chenghuzi** [comment]
@krystofcelba  Thanks for doing this! I've test the new build, and it works well with my MBP2015. But after a restart, the flashlight start not working again. Such thing happened occasionally before flashlight didn't work on macOS 10.13. Do you have any idea on this issue? 

System info:
macOS 10.13.4 Beta


Update:

After reinstalling flashlight (re-init SpotlightSIMBL), all plugins works well. The problem might be the loading part of SpotlightSIMBL.

**Comment by tsimmons** [comment]
I haven't been able to build Flashlight; I tried cloning the project and checking out your PR (#41) but when I try to build, I get errors:

```
ld: warning: directory not found for option '-L/Users/_xxx/Library/Developer/Xcode/DerivedData/Flashlight-djbjtmwjieqmmvehsncvbijtmdsb/Build/Products/Debug/GRMustache'
ld: warning: directory not found for option '-L/Users/_xxx/Library/Developer/Xcode/DerivedData/Flashlight-djbjtmwjieqmmvehsncvbijtmdsb/Build/Products/Debug/JRSwizzle'
ld: warning: directory not found for option '-L/Users/_xxx/Library/Developer/Xcode/DerivedData/Flashlight-djbjtmwjieqmmvehsncvbijtmdsb/Build/Products/Debug/LetsMove'
ld: warning: directory not found for option '-L/Users/_xxx/Library/Developer/Xcode/DerivedData/Pods-gpoaxpycjinulnbzpvilkgtvohcj/Build/Products/Debug'
ld: library not found for -lGRMustache
```

This is on Sierra using XCode 9.2. Any advice?

**Comment by YonatanAhituv** [comment]
@tsimmons you need to run the python script in the root directory. You'll need to remove the code for signing flashlight though. Had the same issue at first.

**Comment by technolingo** [comment]
Do I also need to install Xcode?

**Comment by w0lfschild** [comment]
The update by @krystofcelba is now live so all you need to do is update in app or download the latest version from my repo.

**Comment by mkormendy** [comment]
Does this also fix the other plugins? FullscreenER seems to not be working still.

**Comment by w0lfschild** [comment]
@mkormendy 

This project does not have to do with mySIMBL plugins. Also FullscreenER does work on 10.13.4 so the issue is probably on your end.

**Comment by jcadogan** [comment]
So I loved the flashlight with the simple install, and would love to use the updated one by @krystofcelba but am very new to the whole GitHub scene. Can anyone point me in the direction of a guide or any tips on how to install the updated version? I LOVE Flashlight, and would love to get it working on high sierra!

**Comment by YonatanAhituv** [comment]
@jcadogan Just follow the instructions in the README. The fix is out.

**Comment by AtomicCoding** [comment]
@w0lfschild Can this issue be closed?

**Comment by samlowry** [comment]
@krystofcelba High Sierra 10.13.4, all installed by readme but not works. Rebooted for sure.

BTW, is mySIMBL.app have to ask permissions for upgrading some components every start? Is it normal?

**Comment by w0lfschild** [comment]
@samlowry If it's asking every start then it's probably failing to install the components in the first place, without the mySIMBL aspect fully installed Flashlight wont work at all.

**Comment by d4hines** [comment]
@w0lfschild, I'm having the same issue as @samlowry on 10.13.6 - I've installed mySimbl, but it asks for permissions every time

![screen shot 2018-08-12 at 7 32 33 pm](https://user-images.githubusercontent.com/25231383/44007590-83de10ee-9e66-11e8-937f-fa7711ffa8ad.png)

And no flashlight plugins seem to work
![screen shot 2018-08-12 at 7 33 50 pm](https://user-images.githubusercontent.com/25231383/44007599-b0502702-9e66-11e8-85b8-bbdce519dbe0.png)

Any special steps I need to take? This would be so awesome to get working!

**Comment by MrDavidG** [comment]
@w0lfschild @d4hines, the same issue with you, and my version is also 10.13.6.

**Comment by nooorris** [comment]
@w0lfschild @MrDavidG I got the same problem, and my version is 10.13.1
