### ISSUE TITLE
Request Timed Out

### ISSUE THREAD

**Issue by samurban1** [w0lfschild/Flashlight#38]
After pressing Install on any plugin, after a minute or so an error message pops up saying "Request timed out" and the plugin does not get installed.
<img width="625" alt="screen shot 2017-12-14 at 4 18 12 pm" src="https://user-images.githubusercontent.com/28639060/34020735-aee5a5ca-e0ea-11e7-8219-300b0369881d.png">

**Comment by w0lfschild** [comment]
Hmm maybe the server the plugins are hosted on was down. Seems to work fine for me.
