### ISSUE TITLE
Provide a search UI for using Flashlight plugins outside of Spotlight in SIP cases

### ISSUE THREAD

**Issue by eruffaldi** [w0lfschild/Flashlight#39]
Flashlight has many interesting and useful features thanks to plugins but at the same time I am not going to disable SIP for installing SIMBL. 

I think that it would be great to make a simple UI that triggers a search box directly controlled by Flashlight. This would allow to reuse all the great work done by plugin developers in the past. 

Best Regards,
Emanuele Ruffaldi

**Comment by lincolnaleixo** [comment]
agree

**Comment by w0lfschild** [comment]
Why not just use something like [Alfred](https://www.alfredapp.com/) if you're not going to use the native Spotlight?

**Comment by ghost** [comment]
@w0lfschild This. The best part of Flashlight is that it improves Spotlight, not replaces it.
