### ISSUE TITLE
SIMBL install failed! (High Sierra)

### ISSUE THREAD

**Issue by davronakil** [w0lfschild/Flashlight#40]
> Something went wrong, probably System Integrity Protection.

Trying to get Flashlight to work to no avail. SIMBL runs, but will not install. Attaching a screenshot. 

<img width="729" alt="screen shot 2018-02-06 at 19 56 31" src="https://user-images.githubusercontent.com/3535504/35858568-db9fc21e-0b77-11e8-8f89-00265b9cd0d6.png">

**Comment by yannicklamprecht** [comment]
Did you deactivated SIP?
https://apple.stackexchange.com/questions/208478/how-do-i-disable-system-integrity-protection-sip-aka-rootless-on-macos-os-x

**Comment by w0lfschild** [comment]
This is a mySIMBL issue not Flashlight.
