### ISSUE TITLE
Flashlight commands not working in 10.12.6

### ISSUE THREAD

**Issue by trevorwelch** [w0lfschild/Flashlight#48]
I saw https://github.com/w0lfschild/Flashlight/issues/35 and made sure to `csrutil disable` from the Recovery terminal. Tried reinstalling and restarting a couple of times.

**Comment by ghost-bub** [comment]
I can second this. Actually, spotlight as it is now is practically broken for me. When I try to type anything more than 5 characters, spotlight disappears and the menu bar adjusts as if something is trying to be added to it, but then it reverts to normal.

I'm going to try uninstalling and reinstalling but this is not encouraging...

**Comment by tsimmons** [comment]
@ghost-bub You might try unticking "Bookmarks & History" in the Spotlight preferences; that was my primary issue with crashing Spotlight in Sierra -- see [this link](https://discussions.apple.com/thread/8546951) for more details.

**Comment by ghost-bub** [comment]
@tsimmons That worked to a T. Glad to have Flashlight + Spotlight working again. Everything appears stable on my end, I'm able to do what I was on 10.11.6 so far.
