### ISSUE TITLE
Update Flashlight to use environment Python instead of hardcode /usr/bin/python

### ISSUE THREAD

**Issue by tsimmons** [w0lfschild/Flashlight#51]
I've tried to build Flashlight myself (I get to the linking stage and the linker dies on missing library/directories for GRMustache, JSSwizzle, LetsMove and Pods) ... I was just trying to modify FlashlightResult.m to use  https://github.com/w0lfschild/Flashlight/blob/master/FlashlightApp/FlashlightKit/FlashlightKit/FlashlightResult.m#L54

    task.launchPath = @"/usr/bin/env python";

in order to use the Python installed by Macports (or Homebrew or whatever) since the built-in Python for Sierra is 2.7.10 (which doesn't even do TLS 1.2); So I guess my questions are:

Any advice on how to setup to properly build Flashlight given those other dependencies?

Any chance of getting a build that invokes Python using env instead of hard-coding it? I have already updated the Python scripts in Flashlight.app.

**EDIT**
I remembered how to build Flashlight, but with my changes it still invokes the OS-bundled Python. Is this something that would have to be addressed in mySIMBL?

Thanks &
Cheers,

Toby

**Comment by ignatremizov** [comment]
I have the same request! I was trying to figure out why my modified plugin wasn't running at all, found out it was running the system's default Python 2.7.16 and not my brew's python version 3.7.4. 

As an idea, maybe it could be possible to specify the Python executable for the script as part of the info.json file? Or is that impossible without an update to all of the Python code within Flashlight? I'm not 100% sure yet on how code written for Python 2 and code written for Python 3 within the same project will behave. I'll just write it with the older Python for now, but tips on how to build the project with Python 3 in mind will be greatly appreciated!

**Comment by w0lfschild** [comment]
Resolved in : https://github.com/w0lfschild/Flashlight/pull/66

Update will be out soon.
