### ISSUE TITLE
Can't get it to work on Mojave 10.14.1

### ISSUE THREAD

**Issue by AnthoPakPak** [w0lfschild/Flashlight#52]
Hi @w0lfschild !

I've been using Flashlight a lot on High Sierra. I've just made the update to Mojave since I've seen successful installation reports of Flashlight.
But unfortunately, I can't get it to work… Did I miss something ?

I've tried disabling SIP, even if it wasn't require on High Sierra, but it didn't help.
I've also tried uninstalling mySIMBL and Flashlight then reinstall, still doesn't work…

Please help, I can't live without Flashlight !

Here are my System Info from mySIMBL :
![image](https://user-images.githubusercontent.com/16854916/49249061-98398180-f41b-11e8-9cec-a37f13dc2755.png)

**Comment by AnthoPakPak** [comment]
I've just got it to work by disabling AMFI. I've already tried before but as SIP was still enabled it could toggle AMFI. 
And from what I see, mySIMBL now requires both to be disabled…
Can you confirm that plugins (especially Flashlight) can't work with SIP enabled ?…

Thanks.

**Comment by w0lfschild** [comment]
On Mojave nothing will work with SIP enabled.

**Comment by AnthoPakPak** [comment]
Too bad… Thanks for your answer and keep up the great work 💪

**Comment by ehausen** [comment]
@AnthoPakPak How did you manage to disable AMFI? When I try to click. This happens:
![image](https://user-images.githubusercontent.com/6204129/53493227-88295080-3aa3-11e9-8e83-6281c7828981.png)

**Comment by AnthoPakPak** [comment]
@ehausen Hum, can't remember… Maybe try rebooting and retry. I ended up using Alfred instead of Flashlight because of SIP.
