### ISSUE TITLE
No found plugins in mySIMBL

### ISSUE THREAD

**Issue by Ru7z** [w0lfschild/Flashlight#6]
Hi.
I've installed mySIMBL.But i fount that there is no plugins in mySIMBL.What should i do?

![](http://oai8l5dzh.bkt.clouddn.com/87D4E048-040A-4604-8F1F-2386D75CE54D.png)

**Comment by w0lfschild** [comment]
Well have you opened flashlight as well? If you have then maybe something is preventing the file from being installed.

Make sure that the folder **`/Library/Application Support/SIMBL/Plugins/`** exists and you can manually install the plugin from **`/Applications/Flashlight.app/Contents/Resources/SpotlightSIMBL.bundle`**

Hope that helps.

**Comment by Ru7z** [comment]
Thanks a lot.
