### ISSUE TITLE
Flashlight don't work after reboot on Mojave 10.14.4

### ISSUE THREAD

**Issue by gzqx** [w0lfschild/Flashlight#60]
Flashlight worked properly after first installation but after a reboot it stopped working.
On Mojave 10.14.4 and with SIP disabled.
Have tried reinstall both SIMBL and Flashlight

**Comment by mikadocat** [comment]
It works fine for me. Take a look at:

System Preferences>Security & Privacy>Privacy>Automation

Do you have 'Spotlight' check marked under 'mySIMBL.app'?

**Comment by gzqx** [comment]
Yes, I do......
Another reinstall and reboot suddenly solved all the problems. That's weird ..... any way thank you very much.
