### ISSUE TITLE
Stopped working after Macforge installed on Mojave

### ISSUE THREAD

**Issue by tsimmons** [w0lfschild/Flashlight#64]
Flashlight was working fine under Sierra, version 1.1.0 of Flashlight and whatever the latest release of mySimbl was. I upgraded from Sierra to Mojave and Flashlight worked most of the time (occasionally had to disable and reenable because it would bugger up Spotlight results occasionally, but that was typical under Sierra as well.)

I thought that maybe I should update to the new Macforge way of doing things, so I uninstalled both Flashlight and mySimbl and downloaded Macforge and Flashlight again; going through the installation went fine and Macforge shows it is installed, Flashlight shows it is enabled, but now it appears none of my installed Flashlight plugins are working. I just get normal Spotlight results. Launching Flashlight indicates that it is enabled, but entering any of the installed-Flashlight shortcuts I have installed (emoji, weather, wiki, google) seem to work. Again, I'm just getting Spotlight search results.

Any advice? I'm happy to debug it.

**Comment by tsimmons** [comment]
Additionally: Mojave v10.14.6; SIP and AMFI are disabled; MacForge BETA v0.13.1 (2349); Flashlight v1.1.0;

**Comment by w0lfschild** [comment]
I'm guessing maybe the file 

`/Applications/Flashlight.app/Contents/Resources/SpotlightSIMBL.bundle`

Needs to be placed in 

`/Library/Application Support/MacEnhance/Plugins/`

**Comment by tsimmons** [comment]
I’ll give that a try and post back. Are there advantages (other than getting on the current project) to using MacForge over mySIMBL if all I use is Flashlight?

**Comment by w0lfschild** [comment]
The advantage is that mySIMBL is no longer supported and as far as I know it doesn't work on Catalina. Any issues with mySIMBL will not be fixed.

**Comment by tsimmons** [comment]
Manually copying 

`/Applications/Flashlight.app/Contents/Resources/SpotlightSIMBL.bundle`

to

`/Library/Application Support/MacEnhance/Plugins/`

did the trick (I just used Finder to copy it.) Thanks.
