### ISSUE TITLE
Triggering Open URL plugin crashes Spotlight on Sierra

### ISSUE THREAD

**Issue by jooize** [w0lfschild/Flashlight#7]
## Reproduce
- macOS Sierra 10.12 (16A323)
- mySIMBL 0.3.1
- Flashlight 1.0.3
1. Install Open URL plugin.
2. Type `twitter.com` in Spotlight.
3. Spotlight crashes and restarts.
4. Uninstall Open URL plugin.
5. Type `twitter.com` in Spotlight.
6. Normal Spotlight behavior.

**Comment by funkyLover** [comment]
the same issue..
this behavior happen with all the flashlight plugin installed

**Comment by Bisewski** [comment]
Sometimes it's hiding the action too: 
![screen shot 2016-10-06 at 13 59 24](https://cloud.githubusercontent.com/assets/1869755/19162156/28b7e72e-8bcd-11e6-8425-6a9e14e080c5.png)

**Comment by fatihturan** [comment]
I have a problem similar to @jooize. When I write a "w" letter then Spotlight crashing. You can check it by this screencast: http://jmp.sh/JiTijZD

**Comment by w0lfschild** [comment]
Yeah I didn't update any plugins, so this isn't surprising to me. I doubt I'll have the time/knowledge to be updating the existing plugins.

**Comment by w0lfschild** [comment]
Should be fixed in the latest release.
