### ISSUE TITLE
Not working on Big Sur

### ISSUE THREAD

**Issue by jappyjan** [w0lfschild/Flashlight#71]
Installed MacForge
Installed Flashlight via MacForge
Installed Plugins (tested many)
No Plugin Results show in Spotlight...

**Comment by w0lfschild** [comment]
There will be no support moving forward for future macOS releases.

Significant changes have been made to Spotlight in Big Sur add that on top of the fact Flashlight was already partly broken in recent releases, around 10.15.5 and beyond, I've decided to discontinue my efforts in this project. There are also not many users 387 on v1.2 according to analytics.

It will remain open source and anyone can make a pull request if they're able to get some semblance of Flashlight working on macOS 11.0 but at this point Flashlight is dead.

💀

I'll edit the README and listing on MacForge to indicate 10.15 is EOL for the project sometime here.
