### ISSUE TITLE
Sierra 10.12 not working anymore

### ISSUE THREAD

**Issue by drviver** [w0lfschild/Flashlight#8]
On OSX Sierra 10.12 with the newest Software updates installed, it doesn't work anymore
mySIMBL is working correctly for different tweaks but not Flashlight
It says the plugin is active but there is no difference in Spotlight no matter what Flashlight plugins I install
Tried full reinstall but don't change anything

**Comment by w0lfschild** [comment]
Not sure what the issue is for you it's working for me on 10.12.1 Beta (16B2338c).

**Comment by jingxinxin** [comment]
![image](https://cloud.githubusercontent.com/assets/6293249/19286284/aad7cae2-902f-11e6-8487-9cfe9d887858.png)
On OSX sierra 10.12

**Comment by drviver** [comment]
Disable System Integrity, thats simple

**Comment by mollierobbert** [comment]
Works fine on Sierra after disabling SIP. Issue should be closed.

**Comment by FradSer** [comment]
Works fine on Sierra.
