### ISSUE TITLE
Terminal Plugin not working

### ISSUE THREAD

**Issue by J7mbo** [w0lfschild/Flashlight#9]
I've seen that you won't be doing any work to fix plugins, but I thought I'd mention this as you've accepted PRs for the terminal one so it should be working, but for me it's not.

<img width="677" alt="screen shot 2016-11-08 at 16 42 03" src="https://cloud.githubusercontent.com/assets/2657310/20105558/50bc2f86-a5d2-11e6-91ee-8bad99079b4d.png">

<img width="599" alt="screen shot 2016-11-08 at 16 42 50" src="https://cloud.githubusercontent.com/assets/2657310/20105581/698b29ae-a5d2-11e6-9f3f-1c75034350b9.png">

**Comment by w0lfschild** [comment]
I would have to update the application for any plugin fixes to be applied.

**Comment by waxfingers** [comment]
it works 4 me; have to to open and reinject w mySIMBL each start up though

**Comment by w0lfschild** [comment]
@J7mbo What version of macOS?

**Comment by J7mbo** [comment]
@w0lfschild Sorry for the delay in reply. I haven't tried this since, but I'm always using the latest version. As of right now: 10.12.3

**Comment by J7mbo** [comment]
@w0lfschild I saw this was closed 19 hours ago.

I reinstalled the plugin. Still no data shows with a very simple ping. Very latest version of Mac OS.

**Comment by J7mbo** [comment]
![screen shot 2018-03-18 at 16 12 56](https://user-images.githubusercontent.com/2657310/37567448-5b4d8078-2ac7-11e8-8aad-444da1741845.png)

Will this not actually run *within that black window* there??

**Comment by w0lfschild** [comment]
No unfortunately not, you have to click enter/return and it will open in a new Terminal window.
